language: node_js

os:
  - linux

jobs:
  include:
    - stage: Testing (node 12)
      node_js: 12
      if: type = pull_request
      before_script:
        - npm run lint
      install:
        - npm install
      script:
        - npm run test
